import { runCompete as runDay1First } from './day1First/compete';
import { runCompete as runDay1Second } from './day1Second/compete';
import { runCompete as runDay2First } from './day2First/compete';
import { runCompete as runDay2Second } from './day2Second/compete';
import { runCompete as runDay3First } from './day3First/compete';
import { runCompete as runDay3Second } from './day3Second/compete';
import { runCompete as runDay4First } from './day4First/compete';
import { runCompete as runDay4Second } from './day4Second/compete';
import { runCompete as runDay5First } from './day5First/compete';
import { runCompete as runDay5Second } from './day5Second/compete';
import { runCompete as runDay6First } from './day6First/compete';
import { runCompete as runDay6Second } from './day6Second/compete';
import { runCompete as runDay7First } from './day7First/compete';
import { runCompete as runDay7Second } from './day7Second/compete';
import { runCompete as runDay8First } from './day8First/compete';
import { runCompete as runDay8Second } from './day8Second/compete';
import { runCompete as runDay9First } from './day9First/compete';
import { runCompete as runDay9Second } from './day9Second/compete';
import { runCompete as runDay10First } from './day10First/compete';
import { runCompete as runDay10Second } from './day10Second/compete';
import { runCompete as runDay11First } from './day11First/compete';
import { runCompete as runDay11Second } from './day11Second/compete';
import { runCompete as runDay12First } from './day12First/compete';
import { runCompete as runDay12Second } from './day12Second/compete';
import { runCompete as runDay13First } from './day13First/compete';
import { runCompete as runDay13Second } from './day13Second/compete';
import { runCompete as runDay14First } from './day14First/compete';
import { runCompete as runDay14Second } from './day14Second/compete';
import { runCompete as runDay15First } from './day15First/compete';
// import { runCompete as runDay15Second } from './day15Second/compete';

function main(): void {
	console.log(`> run from ${process.cwd()}\n`);
	runDay1First();
	runDay1Second();
	runDay2First();
	runDay2Second();
	runDay3First();
	runDay3Second();
	runDay4First();
	runDay4Second();
	runDay5First();
	runDay5Second();
	runDay6First();
	runDay6Second();
	runDay7First();
	runDay7Second();
	runDay8First();
	runDay8Second();
	runDay9First();
	runDay9Second();
	runDay10First();
	runDay10Second();
	runDay11First();
	runDay11Second();
	runDay12First();
	runDay12Second();
	runDay13First();
	runDay13Second();
	runDay14First();
	runDay14Second();
	// runDay15First();
}

main();
